variable "nic_name" {}
variable "location" {}
variable "rg_name" {}
variable "private_ip_address_allocation" {}
variable "private_ip_address" {}
variable "biz_application" {}
variable "application_service" {}
variable "costcester" {}
variable "creationdate" {}
variables "subnet_name" {}
variables "vnet_name" {}
variables "rg_name" {}